name: ci-fastify-fullcycle
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/typescript-action@v1
        with:
          milliseconds: 1000
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
      - run: node build/server.js