name: ci-fastify-fullcycle
on: 
  pull_request:
    branches:
      - development
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Main branch   
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: wallghost/ci-node-fullcycle:latest
      
      - name: Installing PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Installing Project Dependencies
        run: pnpm install
      
      - name: Running Build
        run: pnpm run build